### PR TITLE
Create version for 5.0.0

### PR DESCRIPTION
**Pull request by XavierRaynaud**

### CODE REVIEW

**Review by fallen — APPROVED** [review]
lgtm!

**Comment by dkm** [comment]
Ping me if you need me to update the compilers we have on compiler explorer. I see you're also building LLVM here: we can also add it if needed.

**Comment by XavierRaynaud** [comment]
Many thanks @dkm . Fore sure, I will ping you :)

**Comment by XavierRaynaud** [comment]
@dkm : it's ready !
I will be happy if you can update compiler explorer with this new version.

**Comment by dkm** [comment]
Will do the update for the GCC toolchain then. Guess there's no package for the LLVM one (yet?ever? :shrug: )

**Comment by XavierRaynaud** [comment]
I let @dnsampaio answer this question.

**Comment by dkm** [comment]
ACB 5 will be live shortly on compiler explorer :rocket:

**Comment by XavierRaynaud** [comment]
thanks a lot @dkm !

**Comment by dnsampaio** [comment]
> Will do the update for the GCC toolchain then. Guess there's no package for the LLVM one (yet?ever? 🤷 )

I see no issue in publishing our clang and llvm tools.

**Comment by dkm** [comment]
> > Will do the update for the GCC toolchain then. Guess there's no package for the LLVM one (yet?ever? 🤷 )
> 
> I see no issue in publishing our clang and llvm tools.

If you ever produce any packages, let me know and I'll add them to compiler explorer ;)

**Pull request merged**
