### PR TITLE
Create version for 4.4.0-cd1

### PR DESCRIPTION
**Pull request by XavierRaynaud**

### CODE REVIEW

**Comment by dkm** [comment]
wooops, does not build...

**Comment by dkm** [comment]
`../../../../../newlib/libgloss/kvx-elf/include/machine/kv3/mppa3-80/trace.h:15:10: fatal error: machine/kv3/mppa3-80/v2/trace.h: No such file or directory`

**Comment by thvnx** [comment]
Should we close this one?

**Comment by thvnx** [comment]
I guess this is obsolete. I close it but do not hesitate to reopen it if I'm wrong!

**Pull request closed without merging**
